#
# Makefile for the fingerprint drivers.
#

obj-y	+=  fp_drv/

obj-$(CONFIG_FINGERPRINT_GOODIX_GFX1XM)		+= gfx1xm/

obj-$(CONFIG_FINGERPRINT_GOODIX_GFX1XM_QSEE)	+= gfx1xm_qsee/

obj-$(CONFIG_FINGERPRINT_ELAN)		+= elan/


